### ISSUE TITLE
Refactoring des onglets de la démarche: le formulaire de vote doit être disponible uniquement par acces par lien direct

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#414]
L'onglet de vote disparaît, le formulaire de vote (accessible aux utilisateur sans compte) est affiché uniquement pour des URLs avec un paramètre spécifique.

**Comment by slauriere** [comment]
Le comportement suivant a été implémenté (je recopie le message de commit) :
- If the user is guest: if parameter "key" is present in the URL, display only the avis form; if it isn't and if a Cerfa numérique is available for the current démarche, display it; otherwise, redirect to home page.
- If the user is authentified: display the tabs the user is authorized to see.

**Comment by slauriere** [comment]
Concernant la redirection vers la page d'accueil plutôt que la page d'identification : une option serait peut-être de protéger l'accès à la page d'accueil elle-même si elle ne doit pas être visible, ce qui conduirait à une redirection vers la page d'identification.

**Comment by slauriere** [comment]
Réouverture pour traiter l'affichage des différentes étapes du formulaire.

**Comment by slauriere** [comment]
Le formulaire s'affiche bien à présent dés lors que le processus de soumission d'avis a démarré, même si la clef d'API elle-même n'est plus présente dans l'URL.
