### ISSUE TITLE
Use wildcard by default in search completion

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#42]
Following a discussion with Ludo:
- When a user enters "dem" in the suggest box, we should trigger a search on "dem*" similarly to what Google does.
- It if works fine indeed, we may consider adding a wild card to all the words typed in the general search field itself.
- We may consider setting up this behaviour in the product, with an option to activate / deactivate wildcard search.

**Comment by lucaa** [comment]
This issue deserves some additional clarification:

> similarly to what Google does

Note that, as far as I remember, google does not suggest search _results_ but search _terms_: when you start typing, google is suggesting searches done by people in the past that correspond to the text you're typing: it's not a real search of pages that match the partial word that you typed, it's a simple match of other searches based on what you started typing, to try to guess what you mean by your search: do you mean the full word, do you mean only part of it? Note that the real results are only fetched when you hit enter (which is interpreted as an "end of typing" and a comittment to a search string).

Now, about adding the wildcard:
* if we add the wildcard only for the searches we do for the search suggest, we will have a problem when the user will click "see all results" and see different results than the ones they were seeing as suggestions
  * we could add the wildcard in the final search as well (always add wild card) but this will become problematic for a multiword search (or search with operators) and also I'm not a big fan of searching for * in general, because it matches everything and the search does not make sense anymore

**Comment by lucaa** [comment]
So, I tried to add a * in the search by default, and to keep this * in the full search (like what jira does): 

See these screenshots:
![selection_026](https://user-images.githubusercontent.com/657716/41462871-9af6f89a-7094-11e8-8f23-15d35244fb9e.png)
![selection_027](https://user-images.githubusercontent.com/657716/41462874-9e0e2648-7094-11e8-9aab-1042d4b9f73b.png)
![selection_028](https://user-images.githubusercontent.com/657716/41462878-a12eee52-7094-11e8-88b5-eb292fc8fc1a.png)

However, from what I noticed when analysing the search results, lots of the results have similar scores, there seems to be no weight computing, so for now I am trying a different strategy to make the search coherent: I hide the "no results" message: I just don't display anything as long as there are no results, and I restrict the URL search to strings of at least a number of characters.

**Comment by lucaa** [comment]
So, as written here 
https://wiki.apache.org/solr/SolrQuerySyntax#Differences_From_Lucene_Query_Parser and here https://stackoverflow.com/questions/17273756/understanding-wildcard-in-solr , apparently it's normal that wildcard queries all score the same.

Also, there is no analysis on wildcarded words: "impots*" will not match "impot" while "impots" would. This is quite of a blocker to the idea of making pure wildcard searches.

Thus, another idea is to search for the input itself followed by the input itself with a star. E.g. if the user types subv, we'd search for "subv subv*", which would behave as follows:
* if any result contains subv itself, it will show up in results list, with a rather high score - from what I noticed
* all results that contain something that starts with subv will show up in the results as well, but under these first results that match the word itself.

Now, this is reasonable to do for the suggest, but it raises a couple of problems:
* when the user hits "trouver ma demarche", what should we search for in the full results list? Should we do like jira and send the actual search that we're doing?
* should we handle search syntax? (for example, modifiers or searches in quotes) How?

**Comment by lucaa** [comment]
Finally found a solution that mostly makes sense, as follows:
* whenever the user types a search, the part of this search after the last whitespace is extracted, assuming that if there is a whitespace in the search string, the first word of the search was typed fully
* if this part of search contains only alphanumeric characters, it receives a * and it's appended to the search, otherwise nothing is appended to the search.

This rule is applied both for the search of suggestions and for the  full search, with the objective of always having matching results for the 2: the results that appear in suggestions must appear, in the same order, in the full search.

Thus, if the user types "mode", the search that will be performed is "mode mode*" , matching with tf/idf score the results containing the full word "mode" and then, with fixed score, all results that contain "mode" as prefix. Normally, the tf/idf match will be higher than the score of 1 of the wildcard match, and thus the results for the full word "mode" will appear above.
Note that the same will happen when a full word will be typed (impot), impot* will also be searched for.
By the rule described above, the user types "impots decla" , the actual performed search will be "impots decla decla*".
Finally, if the user types "declaration impot" (including the quotes), in order to perform an exact search, the prefixing will not apply at all. Same if the user types "agri*" themselves, the prefixing only applies for words that contain only letters and numbers.
